module.export={
SET_USER_AUTH_INFO: 'SET_USER_AUTH_INFO',
SET_LOADER_LOGIN: 'SET_LOADER_LOGIN',
CLEAR_SIGININ_RESPONSE: 'CLEAR_SIGININ_RESPONSE',
SAVE_USER_NAME: 'SAVE_USER_NAME',
SET_LOGIN_ERROR: 'SET_LOGIN_ERROR'
}
