# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HappyTimes' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HappyTimes
    pod 'Firebase/Core'



  target 'HappyTimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'HappyTimes-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HappyTimes-tvOS

  target 'HappyTimes-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
